# Python libraries and an introduction to data manipulation

The core Python language is by design somewhat minimal.  Like other programming languages, Python has an ecosystem of modules (libraries of code) that augument the base language.  Some of these libraries are "standard", meaning that they are included with your Python distribution.  Many other open source libraries can be obtained from the organizations that support their development.

Think of a library as a collection of functions and data types that can be accessed to complete certain programming tasks without having to implement everything yourself from scratch.

This course will make extensive use of the following libraries:

* **[Numpy](http://numpy.org)** is a library for working with arrays of data.

* **[Pandas](http://pandas.pydata.org)** provides high-performance, easy-to-use data structures and data analysis tools.

* **[Scipy](http://scipy.org)** is a library of techniques for numerical and scientific computing.

* **[Matplotlib](http://matplotlib.org)** is a library for making graphs.

* **[Seaborn](http://seaborn.pydata.org)** is a higher-level interface to Matplotlib that can be used to simplify many graphing tasks.

* **[Statsmodels](http://www.statsmodels.org)** is a library that implements many statistical techniques.

This notebook introduces the Pandas and Numpy libraries, which are used to manipulate datasets.  Next week we will give an overview of the Matplotlib and Seaborn libraries that are used to produce graphs.  The Statsmodels package will be used in the second and third courses of the series that introduce formal statistical analysis and modeling.

# Documentation

No data scientist or software engineer memorizes every feature of every software tool that they utilize.  Effective data scientists take advantage of resources (mostly on-line) to resolve challenges that they encounter when developing code and analyzing data.  Documentation is the official, authoritative resource for any programming language or library. Here are links to the official documentation for the [Python language](https://docs.python.org/3/) and the [Python Standard Library](https://docs.python.org/3/library/index.html#library-index).

### Importing libraries

When using Python, you will generally begin your scripts by importing the libraries that you will be using.

The following statements import the Numpy and Pandas libraries, giving them abbreviated names:

In [1]:
import numpy as np
import pandas as pd

### Utilizing library functions

After importing a library, its functions can then be called from your code by prepending the library name to the function name.  For example, to use the '`dot`' function from the '`numpy`' library, you would enter '`numpy.dot`'.  To avoid repeatedly having to type the libary name in your scripts, it is conventional to define a two or three letter abbreviation for each library, e.g. '`numpy`' is usually abbreviated as '`np`'.  This allows us to use '`np.dot`' instead of '`numpy.dot`'.  Similarly, the Pandas library is typically abbreviated as '`pd`'.

The next cell shows how to call functions from an imported library:

In [3]:
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(a)
np.mean(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


5.0

As you can see, we first used the `array` function from the numpy library to create a literal 1-dimensional array, and then used the `mean` function from the library to calculate its average value (this is called a "literal" array because the data are entered directly into the notebook).

## NumPy

NumPy is a fundamental package for scientific computing with Python. It includes data types for vectors, matrices, and higher-order arrays (tensors), and many commonly-used mathematical functions such as logarithms.

#### Numpy Arrays (the ndarray)

We are mainly interested in the [ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) object which is an n-dimensional array of values, and the methods that allow us to manipulate such arrays.  Recall that a Python list may contain values of different types, e.g. [1, "pig", [3.2, 4.5]] is a Python list containing three elements -- an integer, a string, and another list that itself contains two floating point values.  Lists containing inhomogeneous types are convenient, but do not perform well for large-scale numerical computing.  The numpy ndarray is a homogeneous array that may have any number of axes.  Since it is homogeneous, all values in one ndarray must have the same data type (e.g. all values are integers, or all are floating point numbers).

A numpy array is a table of values that may have any number of "axes".  A 1-dimensional numpy array has a single axis, and is somewhat analogous to a Python list or a mathematical vector.  A 2-dimensional numpy array has two axes, and can be seen as a table or matrix.  Higher-order arrays (tensors) can be useful in specific cases, but are not encountered as often.  As noted above, all values in a Numpy array have the same data type.  Numpy arrays are indexed by a sequence of zero-based integer positions -- that is, `x[0]` is the first element of the 1-d array `x`. The number of axes (dimensions) is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

Below are some one-line expressions that illustrate basic usage of Numpy.

In [5]:
### Create a rank-1 numpy array with 1 axes of length 3.
a = np.array([1, 2, 3])

In [6]:
### Print object type
print("type(a) =", type(a))

type(a) = <class 'numpy.ndarray'>


In [7]:
### Print shape
print("\na.shape =", a.shape)


a.shape = (3,)


In [8]:
### Print some values in a
print("Values in a: ", a[0], a[1], a[2])

Values in a:  1 2 3


In [13]:
### Create a 2x2 numpy array
b = np.array([[1, 2], [3, 4]]) # Must be in a nested list - list of lists
print("b.shape =", b.shape)

b.shape = (2, 2)


In [15]:
## Print some values in b
print("\nValues in b: ", b[0, 0], b[0, 1], b[1, 1])


Values in b:  1 2 4


In [16]:
### Create a 3x2 numpy array
c = np.array([[1, 2], [3, 4], [5, 6]])

In [17]:
### Print shape
print("c.shape =", c.shape)

c.shape = (3, 2)


In [18]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
### Print some values in c
print("\nValues in c: ", c[0, 1], c[1, 0], c[2, 0], c[2, 1])


Values in c:  2 3 5 6


In [22]:
### 2x3 array containing zeros
d = np.zeros((2, 3))
print("d =\n", d)

### 4x2 array of ones
e = np.ones((4, 2))
print("\ne =\n", e)

### 2x2 constant array
f = np.full((2, 2), 9) # 2 x 2 array of 9's
print("\nf =\n", f)

### 3x3 random array
g = np.random.random((3, 3))
print("\ng =\n", g) # adding multiple new lines

### 2x2 array with uninitialized values
h = np.empty((2, 2))
print("\nh =\n", h)

d =
 [[0. 0. 0.]
 [0. 0. 0.]]

e =
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

f =
 [[9 9]
 [9 9]]

g =
 [[0.57389469 0.65180547 0.67226907]
 [0.70361805 0.41608285 0.85536112]
 [0.66490999 0.37744575 0.95828249]]

h =
 [[4.77566392e-310 0.00000000e+000]
 [6.63477093e-310 6.63483041e-310]]


#### Array Indexing and aliasing

It is important to note that Python arrays may share memory, in which case changing the values in one array may alter values in another array.

In [23]:
### Create 3x4 array
h = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("h=\n", h)

h=
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
### Slice array to make a 2x2 sub-array
i = h[:2, 1:3] # select 1st 2 rows, then 2nd and 3rd column - 2, 3 from first list and 6, 7 form 2nd list
print("\ni=\n", i)


i=
 [[2 3]
 [6 7]]


In [26]:
print("\nh[0, 1] =", h[0, 1]) # 1st row, 2nd number


h[0, 1] = 2


In [29]:
### Modify the slice
i[0, 0] = 1738
print (i)
### Print to show how modifying the slice also changes the base object
print("\nh[0, 1] =", h[0, 1]) # First row, 1st coumn

[[1738    3]
 [   6    7]]

h[0, 1] = 1738


If you want to be sure that two arrays do not share memory, use the `copy` method:

In [ ]:
h = np.zeros((3, 3))
i = h[0:2, 0:2].copy()
h[0, 0] = 99
print("h =\n", h)
print("\ni =\n", i)

h =
 [[99.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]

i =
 [[0. 0.]
 [0. 0.]]


#### Datatypes

Numpy arrays are homogeneous, and we can retrieve the data type shared by all elements using the `dtype` attribute.

In [30]:
### Integer
j = np.array([1, 2])
print(j.dtype)

### Float
k = np.array([1.0, 2.0])
print(k.dtype)

### Force Data Type
l = np.array([1.0, 2.0], dtype=np.int64)
print(l.dtype)

int64
float64
int64


Right now you don't need to know a lot about the different numeric data types.  Briefly, `int64` refers to a 64-bit or 8-byte signed integer while `float64` refers to a 64 bit "floating point" value which can approximate any real number.

#### Array arithmetic

Basic mathematical functions operate element-wise on arrays, and are available both using operator symbols (+, -, etc.) and as functions in the numpy module:

In [31]:
x = np.array([[1, 2],[3, 4]], dtype=np.float64)
y = np.array([[5, 6],[7, 8]], dtype=np.float64)

In [32]:
# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print("x + y =\n", x + y)
print(np.add(x, y))

x + y =
 [[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [33]:
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print("\nx - y =\n", x - y)
print(np.subtract(x, y))


x - y =
 [[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [34]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print("\nx * y =\n", x * y)
print(np.multiply(x, y))


x * y =
 [[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [35]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print("\nx / y =\n", x / y)
print(np.divide(x, y))


x / y =
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [36]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print("\nsqrt(x) =\n", np.sqrt(x))


sqrt(x) =
 [[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
x = np.array([[1,2],[3,4]])
print("x =\n", x)

### Compute sum of all elements; prints "10"
print("\nsum(x) =", np.sum(x))

### Compute sum of each column; prints "[4 6]"
print("sum(x, axis=0) =", np.sum(x, axis=0))

### Compute sum of each row; prints "[3 7]"
print("sum(x, axis=1) =", np.sum(x, axis=1))

x =
 [[1 2]
 [3 4]]

sum(x) = 10
sum(x, axis=0) = [4 6]
sum(x, axis=1) = [3 7]


In [ ]:
x = np.array([[1,2],[3,4]])
print("x =\n", x)

### Compute mean of all elements; prints "2.5"
print("\nmean(x) =", np.mean(x))

### Compute mean of each column; prints "[2 3]"
print("mean(x, axis=0) =", np.mean(x, axis=0))

### Compute mean of each row; prints "[1.5 3.5]"
print("mean(x, axis=1) =", np.mean(x, axis=1))

x =
 [[1 2]
 [3 4]]

mean(x) = 2.5
mean(x, axis=0) = [2. 3.]
mean(x, axis=1) = [1.5 3.5]


# Data management with Pandas

Numpy is useful for mathematical calculations in which everything is a number.  In data science we often deal with heterogeneous data including numbers, text, and time values.  Pandas is a library that provides functionality for working with the type of data that frequently arises in real-world data science.  Pandas provides functionality for manipulating data (e.g. transforming values and selecting subsets), summarizing data, reading data to and from files, among many other tasks.

The main data structure that Pandas works with is called a [DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html).  This is a two-dimensional table of data in which the rows typically represent cases or observations (e.g. Cartwheel Contest Participants), and the columns represent variables.  Pandas also has a one-dimensional data structure called a [Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html) that we will encounter when accesing a single column of a Data Frame.

Pandas has a variety of functions named '`read_xxx`' for reading data in different formats from "static" sources such as files.  Right now we will focus on reading '`csv`' files, where "csv" stands for "comma-separated values". A csv file is a lot like a spreadsheet, but it is stored in text form, using commas to "delimit" the values in a given row.  Other important file formats include excel, json, and sql just to name a few.

This is a link to the .csv that we will be exploring in this tutorial: [Cartwheel Data](https://www.coursera.org/learn/understanding-visualization-data/resources/0rVxx) (this link leads to the dataset section of the Resources for this course).  You do not need to download this datafile now since it is already available in Coursera's Jupyter environment.

There are many other options to '`read_csv`' that are very useful.  For example, you would use the option `sep='\t'` instead of the default `sep=','` if the fields of your data file were delimited by tabs instead of commas.  See [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) for the full documentation for '`read_csv`'.

In [37]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Importing data

In [38]:
# The file name string that holds our .csv file
fname = "/content/drive/MyDrive/Colab Notebooks/Statistics with Python Specialization/Course 1 - Understanding and Visualizing Data with Python/work/week1/Cartwheeldata.csv"

# Read the .csv file and store it as a Pandas Data Frame
df = pd.read_csv(fname)

# Print the object type
type(df)

pandas.core.frame.DataFrame

### Viewing data

We can view the top few rows of our Data Frame by calling the head() method.

In [39]:
df.head()

ID  Age Gender  GenderGroup Glasses  GlassesGroup  Height  Wingspan  \
0   1   56      F            1       Y             1    62.0      61.0   
1   2   26      F            1       Y             1    62.0      60.0   
2   3   33      F            1       Y             1    66.0      64.0   
3   4   39      F            1       N             0    64.0      63.0   
4   5   27      M            2       N             0    73.0      75.0   

   CWDistance Complete  CompleteGroup  Score  
0          79        Y              1      7  
1          70        Y              1      8  
2          85        Y              1      7  
3          87        Y              1     10  
4          72        N              0      4

The head() method simply shows the first 5 rows of our Data Frame.  If you want to see, say, the first 10 rows of data, you would pass '10' as an argument to the head method:

In [40]:
df.head(10)

ID  Age Gender  GenderGroup Glasses  GlassesGroup  Height  Wingspan  \
0   1   56      F            1       Y             1    62.0      61.0   
1   2   26      F            1       Y             1    62.0      60.0   
2   3   33      F            1       Y             1    66.0      64.0   
3   4   39      F            1       N             0    64.0      63.0   
4   5   27      M            2       N             0    73.0      75.0   
5   6   24      M            2       N             0    75.0      71.0   
6   7   28      M            2       N             0    75.0      76.0   
7   8   22      F            1       N             0    65.0      62.0   
8   9   29      M            2       Y             1    74.0      73.0   
9  10   33      F            1       Y             1    63.0      60.0   

   CWDistance Complete  CompleteGroup  Score  
0          79        Y              1      7  
1          70        Y              1      8  
2          85        Y              1      7  
3          87        Y              1     10  
4          72        N              0      4  
5          81        N              0      3  
6         107        Y              1     10  
7          98        Y              1      9  
8         106        N              0      5  
9          65        Y              1      8

As you can see, we have a 2-dimensional table of values, where each row is an observation in our cartwheel data, and each column is a variable describing some characteristic of the participants.

To see the column names, access the 'columns' attribute of the data frame:

In [41]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

In a dataframe, each column has a single type, but different columns may have different types.  This is important since datasets in the real world contain variables that may have different types, but within a variable, all observations should have the same type. Access the dtypes attribute of the dataframe to see the data type of each column.

In [42]:
df.dtypes

ID                 int64
Age                int64
Gender            object
GenderGroup        int64
Glasses           object
GlassesGroup       int64
Height           float64
Wingspan         float64
CWDistance         int64
Complete          object
CompleteGroup      int64
Score              int64
dtype: object

### Slicing data frames

Like any table, the rows and columns of a Pandas Data Frame can be referred to by position.  Since Python always counts from 0, the rows and columns are numbered 0, 1, 2, etc.

Pandas Data Frames also have row and column "indexes" that may be more natural to use than numeric positions in many cases.  For example, if our Data Frame contains information about people, we may have a column named "Age".  Although we may know that the age column is in position 3 (the fourth column due to the zero-based indexing), it is generally preferable to access this column by its name ("Age") rather than by its position (3).  One reason for this is that we may at some point manipulate the Data Frame so that the column positions change.

The default index values are simply the positions.  In many cases we do not replace the default row indices with another index, so there is no meaningful difference between label-based and position based row operations.  But most datasets have informative column names, so it is uncommon to encounter a Data Frame that uses the default column indices.

The most common ways to index and select values from Pandas Data Frames are fairly straightforward, but there are also many advanced indexing techniques. See [here](https://pandas.pydata.org/docs/user_guide/indexing.html) for a more complete treatment of this topic.

There are three main ways to "slice" a Data Frame.

1. .loc() -- select based on index values
2. .iloc() -- select based on positions
3. .ix()

Here we will cover the .loc() and .iloc() slicing functions.

### Indexing with .loc()
The .loc() method for a Data Frame takes two indexing values separated by ','. The first indexing value selects rows and the second indexing value selects columns.  An indexing value may be a single index value, a range of index values, or a list containing one or more index values.  Below we provide examples to cover some of the more common use-cases:

In [ ]:
# Return all observations of the variable CWDistance
# df.loc is a method in pandas used to select rows and columns
df.loc[:,"CWDistance"] # :, - select all rows - df.loc[row_labels, column_labels]

0      79
1      70
2      85
3      87
4      72
5      81
6     107
7      98
8     106
9      65
10     96
11     79
12     92
13     66
14     72
15    115
16     90
17     74
18     64
19     85
20     66
21    101
22     82
23     63
24     67
Name: CWDistance, dtype: int64

The following syntax is equivalent to what we used above:

In [ ]:
df["CWDistance"]

0      79
1      70
2      85
3      87
4      72
5      81
6     107
7      98
8     106
9      65
10     96
11     79
12     92
13     66
14     72
15    115
16     90
17     74
18     64
19     85
20     66
21    101
22     82
23     63
24     67
Name: CWDistance, dtype: int64

The following syntax is also equivalent to the preceeding two examples, but is somewhat dispreferred (in rare cases using this syntax can lead to collisions between method names and variable names, and this syntax does not work if you have variable names that include whitespace or punctuation symbols).

In [ ]:
df.CWDistance

0      79
1      70
2      85
3      87
4      72
5      81
6     107
7      98
8     106
9      65
10     96
11     79
12     92
13     66
14     72
15    115
16     90
17     74
18     64
19     85
20     66
21    101
22     82
23     63
24     67
Name: CWDistance, dtype: int64

In the following example we select all rows for multiple columns, ["CWDistance", "Height", "Wingspan"]:

In [ ]:
df.loc[:,["CWDistance", "Height", "Wingspan"]]

CWDistance  Height  Wingspan
0           79   62.00      61.0
1           70   62.00      60.0
2           85   66.00      64.0
3           87   64.00      63.0
4           72   73.00      75.0
5           81   75.00      71.0
6          107   75.00      76.0
7           98   65.00      62.0
8          106   74.00      73.0
9           65   63.00      60.0
10          96   69.50      66.0
11          79   62.75      58.0
12          92   65.00      64.5
13          66   61.50      57.5
14          72   73.00      74.0
15         115   71.00      72.0
16          90   61.50      59.5
17          74   66.00      66.0
18          64   70.00      69.0
19          85   68.00      66.0
20          66   69.00      67.0
21         101   71.00      70.0
22          82   70.00      68.0
23          63   69.00      71.0
24          67   65.00      63.0

The syntax below is equivalent:

In [ ]:
df[["CWDistance", "Height", "Wingspan"]]

CWDistance  Height  Wingspan
0           79   62.00      61.0
1           70   62.00      60.0
2           85   66.00      64.0
3           87   64.00      63.0
4           72   73.00      75.0
5           81   75.00      71.0
6          107   75.00      76.0
7           98   65.00      62.0
8          106   74.00      73.0
9           65   63.00      60.0
10          96   69.50      66.0
11          79   62.75      58.0
12          92   65.00      64.5
13          66   61.50      57.5
14          72   73.00      74.0
15         115   71.00      72.0
16          90   61.50      59.5
17          74   66.00      66.0
18          64   70.00      69.0
19          85   68.00      66.0
20          66   69.00      67.0
21         101   71.00      70.0
22          82   70.00      68.0
23          63   69.00      71.0
24          67   65.00      63.0

In the example below we select a limited range of rows for multiple columns, ["CWDistance", "Height", "Wingspan"].  Note that we are using the default row index values which coincide with the row positions.

In [ ]:
df.loc[:9, ["CWDistance", "Height", "Wingspan"]]

CWDistance  Height  Wingspan
0          79    62.0      61.0
1          70    62.0      60.0
2          85    66.0      64.0
3          87    64.0      63.0
4          72    73.0      75.0
5          81    75.0      71.0
6         107    75.0      76.0
7          98    65.0      62.0
8         106    74.0      73.0
9          65    63.0      60.0

Below we select a limited range of rows for all columns:

In [ ]:
df.loc[10:15]

ID  Age Gender  GenderGroup Glasses  GlassesGroup  Height  Wingspan  \
10  11   30      M            2       Y             1   69.50      66.0   
11  12   28      F            1       Y             1   62.75      58.0   
12  13   25      F            1       Y             1   65.00      64.5   
13  14   23      F            1       N             0   61.50      57.5   
14  15   31      M            2       Y             1   73.00      74.0   
15  16   26      M            2       Y             1   71.00      72.0   

    CWDistance Complete  CompleteGroup  Score  
10          96        Y              1      6  
11          79        Y              1     10  
12          92        Y              1      6  
13          66        Y              1      4  
14          72        Y              1      9  
15         115        Y              1      6

The .loc() function requires two arguments, the indices of the rows and the column names you wish to observe.

In the above case **:** specifies all rows, and our column is **CWDistance**. df.loc[**:**,**"CWDistance"**]

Now, let's say we only want to return the first 10 observations:

In [ ]:
df.loc[:9, "CWDistance"]

0     79
1     70
2     85
3     87
4     72
5     81
6    107
7     98
8    106
9     65
Name: CWDistance, dtype: int64

### Indexing with .iloc()

The .iloc() method is used for position-based slicing. Recall that Python uses zero-based indexing, so the first value is in position zero.  Here are some examples:

In [ ]:
df.iloc[:4]

ID  Age Gender  GenderGroup Glasses  GlassesGroup  Height  Wingspan  \
0   1   56      F            1       Y             1    62.0      61.0   
1   2   26      F            1       Y             1    62.0      60.0   
2   3   33      F            1       Y             1    66.0      64.0   
3   4   39      F            1       N             0    64.0      63.0   

   CWDistance Complete  CompleteGroup  Score  
0          79        Y              1      7  
1          70        Y              1      8  
2          85        Y              1      7  
3          87        Y              1     10

In [ ]:
df.iloc[1:5, 2:4]

Gender  GenderGroup
1      F            1
2      F            1
3      F            1
4      M            2

In the next example, we mix position-based slicing in the rows and label-based indexing in the columns:

In [ ]:
df.iloc[1:5, :][["Gender", "GenderGroup"]]

Gender  GenderGroup
1      F            1
2      F            1
3      F            1
4      M            2

We can view the data types of our data frame columns with by viewing the .dtypes attribute of our data frame:

In [ ]:
df.dtypes

ID                 int64
Age                int64
Gender            object
GenderGroup        int64
Glasses           object
GlassesGroup       int64
Height           float64
Wingspan         float64
CWDistance         int64
Complete          object
CompleteGroup      int64
Score              int64
dtype: object

The result indicates we have integers, floats, and objects with our Data Frame.  A variable with "object" dtype often contains strings, but may in some cases contain other values that are "wrapped" as Python values.

We may also want to observe the different unique values within a specific column, let's do this for the `Gender` variable:

In [ ]:
# List unique values in the df['Gender'] column
df["Gender"].unique()

array(['F', 'M'], dtype=object)

There is another variable called `GenderGroup`, let's consider this variable as well:

In [ ]:
df["GenderGroup"].unique()

array([1, 2])

It seems that these two variables may contain redundant information. Let's explore this further by displaying only these two columns:

In [ ]:
df[["Gender", "GenderGroup"]]

Gender  GenderGroup
0       F            1
1       F            1
2       F            1
3       F            1
4       M            2
5       M            2
6       M            2
7       F            1
8       M            2
9       F            1
10      M            2
11      F            1
12      F            1
13      F            1
14      M            2
15      M            2
16      F            1
17      M            2
18      M            2
19      F            1
20      M            2
21      M            2
22      M            2
23      M            2
24      F            1

From inspecting this output, it seems that these variables contain the same information in different coding schemes.  We can further confirm this hunch using the [crosstab](https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html) function in Pandas:

In [ ]:
pd.crosstab(df["Gender"], df["GenderGroup"])

GenderGroup   1   2
Gender             
F            12   0
M             0  13

From the result above, it is clear that everyone whose Gender is "F" has a GenderGroup value of 1, and everyone whose gender is "M" has a GenderGroup value of 2.

The same result can be obtained using the groupby() and size() methods:

In [ ]:
df.groupby(['Gender','GenderGroup']).size()

Gender  GenderGroup
F       1              12
M       2              13
dtype: int64

Again, the output indicates that we have two combinations:

* Case 1: Gender = F & Gender Group = 1
* Case 2: Gender = M & GenderGroup = 2.  